[startup]
# scene_path = "assets/sponza_tg.glb"
scene_path = "assets/sponza_normal.glb"
# scene_path = "assets/.glb"
[cvars]

# testing possible tables

[init]
[general]
[window]
[export]
[audio]
[scenes]
[input]
[physics]
[renderer]
[materials]
