[startup]
scene_path = "assets/sponza_tg.glb"


# doesnt work
# scene_path = "assets/deccer-cubes/SM_Deccer_Cubes_Colored.glb"

# scene_path = "assets/.glb"
[cvars]

# testing possible tables

[init]
[general]
[window]
[export]
[audio]
[scenes]
[input]
[physics]
[renderer]
[materials]
