[startup]
scene_path = "assets/sponza_tg.glb"
# scene_path = "assets/structure.glb"
# scene_path = "assets/test_cubes.glb"
# scene_path = "assets/more_cubes.glb"
# scene_path = "assets/bistro_gltf/exterior.gltf"
# scene_path = "assets/sponza_1mat.glb"
# scene_path = "assets/bloom_demo2.glb"

# **deccer cubes cementery**
# scene_path = "assets/deccer-cubes/SM_Deccer_Cubes.gltf"
# # scene_path = "assets/deccer-cubes/SM_Deccer_Cubes_Textured.gltf"
# scene_path = "assets/deccer-cubes/SM_Deccer_Cubes_With_Rotation.gltf"
# scene_path = "assets/deccer-cubes/SM_Deccer_Cubes_Textured_Complex.gltf"
# scene_path = "assets/deccer-cubes/SM_Deccer_Cubes_Textured_Embedded.gltf"

# scene_path = "assets/deccer-cubes/SM_Deccer_Cubes_Merged_Texture_Atlas.gltf" # WORKS

# scene_path = "assets/deccer-cubes/SM_Deccer_Cubes.glb"
# scene_path = "assets/deccer-cubes/SM_Deccer_Cubes_Colored.glb"
# scene_path = "assets/deccer-cubes/SM_Deccer_Cubes_Textured.glb"
# scene_path = "assets/deccer-cubes/SM_Deccer_Cubes_With_Rotation.glb"


[cvars]

# testing possible tables

[init]
[general]
[window]
[export]
[audio]
[scenes]
[input]
[physics]
[renderer]
[materials]
