#include "common.h"

#ifndef __cplusplus

layout (local_size_x = 16, local_size_y = 17) in;

layout(set = 0, binding = 0) uniform sampler2D depthImage;
layout(r8, set = 0, binding = 1) uniform image2D outAmbient;

void main()
{
  ivec2 texelCoord = ivec2(gl_GlobalInvocationID.xy);
  ivec2 size = imageSize(outAmbient); // FIXME: put it in pcs

  if (texelCoord.x < size.x && texelCoord.y < size.y)
  {
    imageStore(outAmbient, texelCoord, vec4(0.5, 0.0, 0.0, 0.0));
  }
}

#endif
